GOOGLE_MAPS_API_KEY="AIzaSyB3IQ-JshVms2i8T2St6AQhj3yeX9qA7Js"
GOOGLE_ROUTES_API_KEY="AIzaSyB3IQ-JshVms2i8T2St6AQhj3yeX9qA7Js"

POSTGRES_HOST="45.9.188.86"
POSTGRES_PORT="5432"
POSTGRES_DATABASE="fueltwogo"
POSTGRES_USER="fuel_user"
POSTGRES_PASSWORD="V3ry$tr0ngP@ss!2024"